# Generated by Django 4.1 on 2022-08-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='project name')),
                ('description', models.TextField(blank=True, max_length=2500, null=True, verbose_name='project description')),
                ('likes', models.IntegerField(default=1, verbose_name='number of likes')),
                ('image', models.FileField(blank=True, null=True, upload_to='images', verbose_name='project image')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
