# Generated by Django 4.1 on 2022-09-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(default='images/notfound.jpg', upload_to='images', verbose_name='project image'),
        ),
    ]
