export const PROFILE_GET_SUCCESS = "PROFILE_GET_SUCCESS";
export const PROFILE_GET_FAIL = "PROFILE_GET_FAIL";
export const PROFILE_EDIT_SUCCESS = "PROFILE_EDIT_SUCCESS";
export const PROFILE_EDIT_FAIL = "PROFILE_EDIT_FAIL";

export const SKILLS_GET_SUCCESS = "SKILLS_GET_SUCCESS";
export const SKILLS_GET_FAIL = "SKILLS_GET_FAIL";
export const SKILL_CREATE_SUCCESS = "SKILL_CREATE_SUCCESS";
export const SKILL_CREATE_FAIL = "SKILL_CREATE_FAIL";
export const SKILL_EDIT_SUCCESS = "SKILL_EDIT_SUCCESS";
export const SKILL_EDIT_FAIL = "SKILL_EDIT_FAIL";
export const SKILL_DELETE_SUCCESS = "SKILL_DELETE_SUCCESS";
export const SKILL_DELETE_FAIL = "SKILL_DELETE_FAIL";

export const PROJECTS_GET_SUCCESS = "PROJECTS_GET_SUCCESS";
export const PROJECTS_GET_FAIL = "PROJECTS_GET_FAIL";

export const PROJECT_GET_SUCCESS = "PROJECT_GET_SUCCESS";
export const PROJECT_GET_FAIL = "PROJECT_GET_FAIL";
export const PROJECT_LOADING_DONE = "PROJECT_LOADING_DONE";
export const PROJECT_CREATE_SUCCESS = "PROJECT_CREATE_SUCCESS";
export const PROJECT_CREATE_FAIL = "PROJECT_CREATE_FAIL";
export const PROJECT_EDIT_SUCCESS = "PROJECT_EDIT_SUCCESS";
export const PROJECT_EDIT_FAIL = "PROJECT_EDIT_FAIL";
export const PROJECT_DELETE_SUCCESS = "PROJECT_DELETE_SUCCESS";
export const PROJECT_DELETE_FAIL = "PROJECT_DELETE_FAIL";

export const IMAGES_GET_SUCCESS = "IMAGES_GET_SUCCESS";
export const IMAGES_GET_FAIL = "IMAGES_GET_FAIL";
export const IMAGE_CREATE_SUCCESS = "IMAGE_CREATE_SUCCESS";
export const IMAGE_CREATE_FAIL = "IMAGE_CREATE_FAIL";

export const MESSAGE_GET_SUCCESS = "MESSAGE_GET_SUCCESS";
export const MESSAGE_GET_FAIL = "MESSAGE_GET_FAIL";
export const MESSAGE_SEND_SUCCESS = "MESSAGE_SEND_SUCCESS";
export const MESSAGE_SEND_FAIL = "SEND_MESSAGE_FAIL";

// Auth

export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS";
export const AUTHENTICATED_FAIL = "AUTHENTICATED_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
